server:
  port: 9060
spring:
  application:
    name: gateway

zuul:
  routes:
    api-a-url:
      path: /api/**
      url: http://localhost:9070/
    api2:
      path: /api2/**
      url: http://localhost:9070/
